---
userGroup:       users
defaultGroups:
    - sudo
    - cdrom
    - dip
autologinGroup:  autologin
sudoersGroup:    sudo
setRootPassword: false

passwordRequirements:
    passwordRequirements:
    nonempty: true
    minLength: 8
    maxLength: -1
    libpwquality:
        - minlen=8
        - minclass=2
        - maxrepeat=3

